### ISSUE TITLE
BUG: styles command without folder path

### ISSUE THREAD

**Issue by usrrname** [rangle/radius-workspace#36]
## Reproduction

1. run `npx radius-scripts styles`,
2. Enter `FIGMA_URL` and `FIGMA_TOKEN` and the path that CSS files will be created
Error: I get the following error: 
```
(node:79161) UnhandledPromiseRejectionWarning: Error: node-id not found
    at assert (/Users/jenc/.npm/_npx/79161/lib/node_modules/radius-script/dist/commands/styles/utils/figma.utils.js:65:15)
    at assertFigmaData (/Users/jenc/.npm/_npx/79161/lib/node_modules/radius-script/dist/commands/styles/utils/figma.utils.js:72:24)
    at processFigmaUrl (/Users/jenc/.npm/_npx/79161/lib/node_modules/radius-script/dist/commands/styles/utils/figma.utils.js:82:5)
    at /Users/jenc/.npm/_npx/79161/lib/node_modules/radius-script/dist/commands/styles/lib/radius-styles.js:65:60
    at step (/Users/jenc/.npm/_npx/79161/lib/node_modules/radius-script/dist/commands/styles/lib/radius-styles.js:33:23)
    at Object.next (/Users/jenc/.npm/_npx/79161/lib/node_modules/radius-script/dist/commands/styles/lib/radius-styles.js:14:53)
    at /Users/jenc/.npm/_npx/79161/lib/node_modules/radius-script/dist/commands/styles/lib/radius-styles.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jenc/.npm/_npx/79161/lib/node_modules/radius-script/dist/commands/styles/lib/radius-styles.js:4:12)
    at generateGlobalStyles (/Users/jenc/.npm/_npx/79161/lib/node_modules/radius-script/dist/commands/styles/lib/radius-styles.js:56:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:79161) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:79161) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

This may not be a bug if the default behaviour isn't to create a folder regardless of whether a path is supplied

**Comment by usrrname** [comment]
Confirmed today that this is not an issue
